declare module 'bfj';
declare module 'yoshi-flow-legacy/bin/yoshi-legacy';
declare module 'rtlcss-webpack-plugin';
declare module '@stylable/webpack-plugin';
declare module '@wix/santa-site-renderer-testkit';
declare module 'velocity';
declare module '@wix/wix-experiments/dist/src/laboratory-testkit';
declare module '@wix/wix-base-ui';
declare module '@wix/wix-config-emitter';
