module.exports = {
  extends: [
    require.resolve('eslint-config-prettier'),
    'prettier/@typescript-eslint',
    require.resolve('./test'),
  ],

  parser: 'babel-eslint',

  plugins: ['prettier', 'import'],

  env: {
    commonjs: true,
    es6: true,
    node: true,
  },

  parserOptions: {
    ecmaVersion: 6,
    ecmaFeatures: {
      generators: true,
    },
  },

  rules: {
    // http://eslint.org/docs/rules/
    'array-callback-return': 'warn',
    'default-case': ['warn', { commentPattern: '^no default$' }],
    eqeqeq: ['warn', 'allow-null'],
    'no-array-constructor': 'warn',
    'no-caller': 'warn',
    'no-const-assign': 'warn',
    'no-control-regex': 'warn',
    'no-delete-var': 'warn',
    'no-dupe-args': 'warn',
    'no-dupe-class-members': 'warn',
    'no-dupe-keys': 'warn',
    'no-duplicate-case': 'warn',
    'no-empty-character-class': 'warn',
    'no-empty-pattern': 'warn',
    'no-eval': 'warn',
    'no-ex-assign': 'warn',
    'no-extend-native': 'warn',
    'no-extra-bind': 'warn',
    'no-extra-label': 'warn',
    'no-fallthrough': 'warn',
    'no-func-assign': 'warn',
    'no-implied-eval': 'warn',
    'no-invalid-regexp': 'warn',
    'no-iterator': 'warn',
    'no-label-var': 'warn',
    'no-labels': ['warn', { allowLoop: true, allowSwitch: false }],
    'no-lone-blocks': 'warn',
    'no-loop-func': 'warn',
    'no-multi-str': 'warn',
    'no-native-reassign': 'warn',
    'no-negated-in-lhs': 'warn',
    'no-new-func': 'warn',
    'no-new-object': 'warn',
    'no-new-symbol': 'warn',
    'no-new-wrappers': 'warn',
    'no-obj-calls': 'warn',
    'no-octal': 'warn',
    'no-octal-escape': 'warn',
    'no-redeclare': 'warn',
    'no-regex-spaces': 'warn',
    'no-restricted-syntax': ['warn', 'WithStatement'],
    'no-script-url': 'warn',
    'no-self-assign': 'warn',
    'no-self-compare': 'warn',
    'no-sequences': 'warn',
    'no-shadow': 'warn',
    'no-shadow-restricted-names': 'warn',
    'no-sparse-arrays': 'warn',
    'no-template-curly-in-string': 'warn',
    'no-this-before-super': 'warn',
    'no-throw-literal': 'warn',
    'no-undef': 'error',
    'no-restricted-globals': ['error'],
    'no-unreachable': 'warn',
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
      },
    ],
    'no-unused-labels': 'warn',
    'no-unused-vars': [
      'warn',
      {
        args: 'after-used',
        ignoreRestSiblings: true,
      },
    ],
    'no-use-before-define': [
      'warn',
      {
        functions: false,
        classes: false,
        variables: false,
      },
    ],
    'no-useless-computed-key': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-rename': [
      'warn',
      {
        ignoreDestructuring: false,
        ignoreImport: false,
        ignoreExport: false,
      },
    ],
    'no-var': 'warn',
    'no-with': 'warn',
    'prefer-const': 'warn',
    'require-yield': 'warn',
    strict: ['warn', 'never'],
    'use-isnan': 'warn',
    'valid-typeof': 'warn',
    'getter-return': 'warn',

    // https://github.com/benmosher/eslint-plugin-import
    'import/no-unresolved': ['error', { commonjs: true, caseSensitive: true }],
    'import/no-amd': 'error',
    'import/no-duplicates': 'error',
    'import/newline-after-import': 'error',
    'import/no-absolute-path': 'error',
    'import/no-useless-path-segments': 'error',

    // https://github.com/prettier/eslint-plugin-prettier
    'prettier/prettier': [
      'warn',
      {
        singleQuote: true,
        trailingComma: 'all',
      },
    ],
  },

  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
        ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
        sourceType: 'module', // Allows for the use of imports
      },

      plugins: ['@typescript-eslint'],

      rules: {
        'no-unused-vars': 'off',
        'no-undef': 'off',
        'import/no-unresolved': 'off',
        'no-invalid-this': 0,

        'prettier/prettier': [
          'warn',
          { singleQuote: true, trailingComma: 'all' },
        ],
        'no-useless-constructor': 'error',
        '@typescript-eslint/adjacent-overload-signatures': 'error',
        'no-sequences': 'error',
        '@typescript-eslint/no-namespace': 'error',
        '@typescript-eslint/no-non-null-assertion': 'error',
        '@typescript-eslint/triple-slash-reference': 'error',
        '@typescript-eslint/prefer-for-of': 'error',
        curly: 'error',
        'no-caller': 'error',
        'no-cond-assign': ['error', 'always'],
        'no-new-wrappers': 'error',
        'constructor-super': 'error',
        '@typescript-eslint/no-dynamic-delete': 'error',
        'no-eval': 'error',
        'no-template-curly-in-string': 'error',
        '@typescript-eslint/no-misused-new': 'error',
        'no-return-await': 'error',
        'no-shadow': 'error',
        'dot-notation': 'error',
        'no-fallthrough': 'error',
        'no-unsafe-finally': 'error',
        'no-var': 'error',
        'prefer-object-spread': 'error',
        radix: 'error',
        'default-case': 'error',
        eqeqeq: 'error',
        'use-isnan': 'error',
        'prefer-const': 'error',
        '@typescript-eslint/array-type': ['error', { default: 'array' }],
        '@typescript-eslint/prefer-function-type': 'error',
        '@typescript-eslint/consistent-type-assertions': 'error',
        'no-undef-init': 'error',
        'object-shorthand': 'error',
        '@typescript-eslint/member-delimiter-style': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-empty-character-class': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-extra-semi': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-regex-spaces': 'error',
        'no-unexpected-multiline': 'error',
        'no-proto': 'error',
        'no-script-url': 'error',
        'no-self-compare': 'error',
        'no-duplicate-case': 'error',
        'no-irregular-whitespace': 'error',
        'no-sparse-arrays': 'error',
        'valid-typeof': 'error',
        'no-with': 'error',
        'no-restricted-syntax': ['error', 'SequenceExpression'],
        'import/no-duplicates': 'error',
        'no-throw-literal': 'error',
      },
    },
  ],
};
